### ISSUE TITLE
rename?

### ISSUE THREAD

**Issue by lewang** [magnars/smart-forward.el#2]
is smart-forward really a good name to describe what this does?  Seems something like `er-move` woud be better.

**Comment by lewang** [comment]
Maybe this should be a part of expand-region actually.

**Comment by magnars** [comment]
I agree that the name smart-forward doesn't cover the entirety of what this does, after all there is smart-backwards, up and down too. :-) But then again, the name expand-region isn't entirely accurate either. I think names of packages need to be memorable over precise.

As for folding it into expand-region itself, I this functionality is different enough to warrant its own package. I don't want expand-region to become a mish-mash of halfway related functionality - I want it to continue being about marking semantic units.
